"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

"""
measurement
"""
type Measurement {
  key: ID!
  name: String!
  unit: String!
  value: Float
}

type Query {
  sensor(key: String!): Sensor!
  sensors: [Sensor!]!
}

"""
sensor
"""
type Sensor {
  key: ID!
  measurements: [Measurement!]!
  name: String!
  tags: [Tag!]!
  type: SensorType!
  updated: DateTime
}

enum SensorType {
  HEATING_METER
  POWER_METER
  THERMOMETER
  WATER_METER
}

type Subscription {
  sensorUpdated: Sensor!
}

"""
tag
"""
type Tag {
  key: ID!
  value: String!
}
